export const inputs = [
  {
    name: "business_name",
    displayName: "Business Name",
    type: "text",
    placeholder: "Business Name",
    required: true,
  },
  {
    name: "first_name",
    displayName: "First Name",
    type: "text",
    placeholder: "First Name",
    required: true,
  },
  {
    name: "last_name",
    displayName: "Last Name",
    type: "text",
    placeholder: "Last Name",
    required: true,
  },
  {
    name: "business_phone",
    displayName: "Business Phone Number",
    type: "text",
    placeholder: "Business Phone Number",
    required: true,
  },
  {
    name: "address_line1",
    displayName: "Address Line 1",
    type: "text",
    placeholder: "Address",
    required: true,
  },
  {
    name: "city",
    displayName: "City",
    type: "text",
    placeholder: "City",
    required: true,
  },
  {
    name: "country_id",
    displayName: "Country",
    type: "select",
    placeholder: "Country",
    required: true,
  },
  {
    name: "postal_code",
    displayName: "Postal Code",
    type: "text",
    placeholder: "Postal Code",
    required: true,
  },
  {
    name: "email",
    displayName: "Email",
    type: "email",
    placeholder: "test@example.com",
    required: true,
  },
  {
    name: "email_confirmation",
    displayName: "Confirm Email",
    type: "email",
    placeholder: "test@example.com",
    required: true,
  },
  {
    name: "password",
    displayName: "Password",
    type: "password",
    placeholder: "Password",
    required: true,
  },
  {
    name: "password_confirmation",
    displayName: "Confirm Password",
    type: "password",
    placeholder: "Password confirmation",
    required: true,
  },
];

