export const inputs = [
    {
      name: "businessName",
      displayName: "Business Name",
      type: "text",
      placeholder: "Business Name",
      required: true,
    },
    {
      name: "firstName",
      displayName: "First Name",
      type: "text",
      placeholder: "First Name",
      required: true,
    },
    {
      name: "lastName",
      displayName: "Last Name",
      type: "text",
      placeholder: "Last Name",
      required: true,
    },
    {
      name: "businessPhone",
      displayName: "Business Phone Number",
      type: "text",
      placeholder: "Business Phone Number",
      required: true,
    },
    {
      name: "cellPhone",
      displayName: "Cell Phone Number",
      type: "text",
      placeholder: "Cell Phone Number",
      required: false,
    },
    {
      name: "addressLine1",
      displayName: "Address Line 1",
      type: "text",
      placeholder: "Address",
      required: true,
    },
    {
      name: "apartment",
      displayName: "Apartment, suite, etc",
      type: "text",
      placeholder: "Apartment, suite, etc",
      required: false,
    },
    {
      name: "city",
      displayName: "City",
      type: "text",
      placeholder: "City",
      required: true,
    },
    {
      name: "country",
      displayName: "Country",
      type: "text",
      placeholder: "Country",
      required: true,
    },
    {
      name: "postalCode",
      displayName: "Postal Code",
      type: "text",
      placeholder: "Postal Code",
      required: true,
    },
    {
      name: "email",
      displayName: "Email",
      type: "email",
      placeholder: "test@example.com",
      required: true,
    },
    {
      name: "confirmEmail",
      displayName: "Confirm Email",
      type: "email",
      placeholder: "test@example.com",
      required: true,
    },
    {
      name: "password",
      displayName: "Password",
      type: "password",
      placeholder: "Password",
      required: true,
    },
    {
      name: "confirmPassword",
      displayName: "Confirm Password",
      type: "password",
      placeholder: "Password confirmation",
      required: true,
    },
  ];